//
//  EndScreenViewControllerTests.swift
//  QuizZap
//
//  Created by Tales Conrado on 12/02/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import QuizZap
import XCTest

class EndScreenViewControllerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: EndScreenViewController!
  var window: UIWindow!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    window = UIWindow()
    setupEndScreenViewController()
  }
  
  override func tearDown()
  {
    window = nil
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupEndScreenViewController()
  {
    sut = EndScreenViewController()
  }
  
  func loadView()
  {
    window.addSubview(sut.view)
    RunLoop.current.run(until: Date())
  }
  
  // MARK: Test doubles
  
  class EndScreenBusinessLogicSpy: EndScreenBusinessLogic
  {
    func getScores() {
        
    }
        
  }
  
  // MARK: Tests
  
  func testShouldDoSomethingWhenViewIsLoaded()
  {
    // Given
    let viewModel = EndScreen.ViewModel(highestScore: 1,
                                        highestScoreTotal: 10,
                                        hitRate: 80,
                                        currentScore: 10,
                                        currentTotal: 10)
    loadView()
    _ = sut.view
    
    // When
    sut.displayScores(viewModel: viewModel)
    
    // Then
    XCTAssertEqual("Taxa de acertos de 80.0%", sut.percentageLabel.text)
  }

}
