//
//  EndScreenPresenterTests.swift
//  QuizZap
//
//  Created by Tales Conrado on 12/02/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import QuizZap
import XCTest

class EndScreenPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: EndScreenPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupEndScreenPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupEndScreenPresenter()
  {
    sut = EndScreenPresenter()
  }
  
  // MARK: Test doubles
  
  class EndScreenDisplayLogicSpy: EndScreenDisplayLogic
  {
    func displayScores(viewModel: EndScreen.ViewModel) {
        
    }
    
    var displaySomethingCalled = false

  }
  
  // MARK: Tests
  
  func testPresentSomething()
  {
    // Given
    let spy = EndScreenDisplayLogicSpy()
    sut.displayDelegate = spy
    let response = EndScreen.Response()
    
    // When
    //sut.sendScores(viewModel: )
  }
}
