//
//  EndScreenInteractorTests.swift
//  QuizZap
//
//  Created by Tales Conrado on 12/02/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import QuizZap
import XCTest

class EndScreenInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: EndScreenInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupEndScreenInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupEndScreenInteractor()
  {
    sut = EndScreenInteractor()
  }
  
  // MARK: Test doubles
  
  class EndScreenPresentationLogicSpy: EndScreenPresentationLogic
  {
    
    var sendScoresCalled = false

    func sendScores(viewModel: EndScreen.ViewModel) {
        sendScoresCalled = true
    }
    

  }
  
  // MARK: Tests
  
  func testGetScores()
  {
    let spy = EndScreenPresentationLogicSpy()
    sut.presenter = spy
    sut.getScores()
    
    XCTAssertTrue(spy.sendScoresCalled)
  }
}
