//
//  QuizInteractorTests.swift
//  QuizZap
//
//  Created by Tales Conrado on 03/02/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import QuizZap
import XCTest

class QuizInteractorTests: XCTestCase {
    // MARK: Subject under test

    var sut: QuizInteractor!

    // MARK: Test lifecycle
  
    override func setUp() {
        super.setUp()
        setupQuizInteractor()
    }

    override func tearDown() {
        super.tearDown()
    }
  
    // MARK: Test setup

    func setupQuizInteractor() {
        let worker = QuizAPIWorker()
        sut = QuizInteractor(worker: worker)
    }

    // MARK: Test doubles

    class QuizPresentationLogicSpy: QuizPresentationLogic {
        func quizEnded(score: Int, total: Int) {
            
        }
        
        // TODO: Test
        func quizEnded(score: Int) {
            
        }
        
        var loadQuestionsCalled = false

        func didLoadQuestions(response: Quiz.Response) {
            
        }
        
    }

    // MARK: Tests

    func testGetFirstQuestion() {

    }
}
