//
//  StartInteractorTests.swift
//  QuizZap
//
//  Created by Tales Conrado on 12/02/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import QuizZap
import XCTest

class StartInteractorTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: StartInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        setupStartInteractor()
    }
    
    override func tearDown()
    {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupStartInteractor()
    {
        sut = StartInteractor()
    }
    
    // MARK: Tests
    
    func testSelectDifficulty()
    {
        // Given
        sut.didSelectDifficulty(.easy)
        
        // Then
        XCTAssertEqual(Difficulty.easy, sut.difficultyLevel)
    }
    
    func testSelectNumberOfQuestions() {
        // Given
        sut.didSelectNumberOfQuestions(12)
        
        // Then
        XCTAssertEqual(12, sut.numberOfQuestions)
    }
}
